# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created: Mon Aug 22 16:56:35 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(390, 420)
        Dialog.setMinimumSize(QtCore.QSize(382, 372))
        Dialog.setMaximumSize(QtCore.QSize(390, 420))
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Arx Control Center", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 371, 401))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_4 = QtGui.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 371, 381))
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(80, 100, 211, 191))
        self.frame_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Moire"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pwBox = QtGui.QLineEdit(self.frame_5)
        self.pwBox.setGeometry(QtCore.QRect(20, 111, 171, 20))
        self.pwBox.setStyleSheet(_fromUtf8("background-color: rgb(247, 247, 247);"))
        self.pwBox.setObjectName(_fromUtf8("pwBox"))
        self.loginButton = QtGui.QPushButton(self.frame_5)
        self.loginButton.setGeometry(QtCore.QRect(60, 151, 91, 23))
        self.loginButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 140, 140);"))
        self.loginButton.setText(QtGui.QApplication.translate("Dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.userBox = QtGui.QLineEdit(self.frame_5)
        self.userBox.setGeometry(QtCore.QRect(22, 41, 171, 20))
        self.userBox.setStyleSheet(_fromUtf8("background-color: rgb(247, 247, 247);"))
        self.userBox.setObjectName(_fromUtf8("userBox"))
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(8, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Moire"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.list = QtGui.QListWidget(self.tab)
        self.list.setGeometry(QtCore.QRect(10, 70, 341, 221))
        self.list.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 255);"))
        self.list.setObjectName(_fromUtf8("list"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 71, 16))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.argsBox = QtGui.QLineEdit(self.tab)
        self.argsBox.setGeometry(QtCore.QRect(10, 320, 191, 21))
        self.argsBox.setText(_fromUtf8(""))
        self.argsBox.setObjectName(_fromUtf8("argsBox"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setText(QtGui.QApplication.translate("Dialog", "ArXBot Control Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(210, 320, 81, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "(Tasks)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Update List", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "DDOS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "SynFlood", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "Update Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("Dialog", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("Dialog", "Vaccinate", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 341, 20))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 255);"))
        self.lineEdit.setText(QtGui.QApplication.translate("Dialog", "                      Bots                                                   Task", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(170, 80, 21, 201))
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 255);"))
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(170, 50, 20, 16))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 255);"))
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.exitButton_2 = QtGui.QPushButton(self.tab)
        self.exitButton_2.setGeometry(QtCore.QRect(300, 320, 51, 23))
        self.exitButton_2.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        self.exitButton_2.setText(QtGui.QApplication.translate("Dialog", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton_2.setObjectName(_fromUtf8("exitButton_2"))
        self.output = QtGui.QLabel(self.tab)
        self.output.setGeometry(QtCore.QRect(10, 350, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setText(QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.output.setObjectName(_fromUtf8("output"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 10, 171, 191))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(244, 244, 244);"))
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(70, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "THIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setEnabled(False)
        self.frame_2.setGeometry(QtCore.QRect(190, 10, 161, 191))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(244, 244, 244);"))
        self.frame_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "FEATURE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setEnabled(False)
        self.frame_3.setGeometry(QtCore.QRect(10, 210, 341, 151))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(244, 244, 244);"))
        self.frame_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(100, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "COMING SOON", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(85, 0, 255);"))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Bot Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.output_2 = QtGui.QLabel(self.groupBox)
        self.output_2.setGeometry(QtCore.QRect(20, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_2.setFont(font)
        self.output_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.output_2.setText(QtGui.QApplication.translate("Dialog", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.output_2.setObjectName(_fromUtf8("output_2"))
        self.output_3 = QtGui.QLabel(self.groupBox)
        self.output_3.setGeometry(QtCore.QRect(20, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_3.setFont(font)
        self.output_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.output_3.setText(QtGui.QApplication.translate("Dialog", "Mutex:", None, QtGui.QApplication.UnicodeUTF8))
        self.output_3.setObjectName(_fromUtf8("output_3"))
        self.ipBox = QtGui.QLineEdit(self.groupBox)
        self.ipBox.setGeometry(QtCore.QRect(142, 20, 191, 20))
        self.ipBox.setObjectName(_fromUtf8("ipBox"))
        self.mutexBox = QtGui.QLineEdit(self.groupBox)
        self.mutexBox.setGeometry(QtCore.QRect(140, 50, 191, 20))
        self.mutexBox.setReadOnly(True)
        self.mutexBox.setObjectName(_fromUtf8("mutexBox"))
        self.ranMutexButton = QtGui.QPushButton(self.groupBox)
        self.ranMutexButton.setGeometry(QtCore.QRect(140, 80, 91, 23))
        self.ranMutexButton.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 238);"))
        self.ranMutexButton.setText(QtGui.QApplication.translate("Dialog", "Random Mutex", None, QtGui.QApplication.UnicodeUTF8))
        self.ranMutexButton.setObjectName(_fromUtf8("ranMutexButton"))
        self.buildButton = QtGui.QPushButton(self.groupBox)
        self.buildButton.setGeometry(QtCore.QRect(250, 80, 81, 23))
        self.buildButton.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 238);"))
        self.buildButton.setText(QtGui.QApplication.translate("Dialog", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.buildButton.setObjectName(_fromUtf8("buildButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 341, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("color: rgb(85, 0, 255);"))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "URL Checker", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.output_4 = QtGui.QLabel(self.groupBox_2)
        self.output_4.setGeometry(QtCore.QRect(20, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_4.setFont(font)
        self.output_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.output_4.setText(QtGui.QApplication.translate("Dialog", "URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.output_4.setObjectName(_fromUtf8("output_4"))
        self.URLBox = QtGui.QLineEdit(self.groupBox_2)
        self.URLBox.setGeometry(QtCore.QRect(142, 20, 191, 20))
        self.URLBox.setObjectName(_fromUtf8("URLBox"))
        self.checkButton = QtGui.QPushButton(self.groupBox_2)
        self.checkButton.setGeometry(QtCore.QRect(250, 50, 81, 23))
        self.checkButton.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 238);"))
        self.checkButton.setText(QtGui.QApplication.translate("Dialog", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.checkButton.setObjectName(_fromUtf8("checkButton"))
        self.outputURLChecker = QtGui.QLabel(self.groupBox_2)
        self.outputURLChecker.setGeometry(QtCore.QRect(10, 80, 321, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        font.setItalic(True)
        self.outputURLChecker.setFont(font)
        self.outputURLChecker.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.outputURLChecker.setText(QtGui.QApplication.translate("Dialog", "Waiting for URL to check.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputURLChecker.setAlignment(QtCore.Qt.AlignCenter)
        self.outputURLChecker.setObjectName(_fromUtf8("outputURLChecker"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.loginButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.sLogin)
        QtCore.QObject.connect(self.pwBox, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.loginButton.click)
        QtCore.QObject.connect(self.pwBox, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.loginButton.animateClick)
        QtCore.QObject.connect(self.exitButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.sGo)
        QtCore.QObject.connect(self.buildButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.sBuild)
        QtCore.QObject.connect(self.ranMutexButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.sRanMutex)
        QtCore.QObject.connect(self.checkButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.sCheckURL)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.userBox, self.pwBox)
        Dialog.setTabOrder(self.pwBox, self.loginButton)
        Dialog.setTabOrder(self.loginButton, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.list)
        Dialog.setTabOrder(self.list, self.argsBox)

    def retranslateUi(self, Dialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Bot Control", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Account Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Tools", None, QtGui.QApplication.UnicodeUTF8))

